CREATE TABLE [dbo].[Table]
(
	[Id] INT NULL PRIMARY KEY, 
    [FIRST NAME] VARCHAR(50) NULL, 
    [MIDDLE NAME] VARCHAR(50) NULL, 
    [LAST NAME] VARCHAR(50) NULL, 
    [ADDRESS] VARCHAR(250) NULL, 
    [CONTACT NO.] VARCHAR(50) NULL, 
    [GENDER] VARCHAR(50) NULL, 
    [EMAIL] VARCHAR(50) NULL
)
